pipeline {
    agent any
 
    tools {
        maven 'Maven3'
        jdk  'JDK'
    }
 
    stages {
 
        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/codingwithdev28/DemocartAssign.git'
            }
        }
 
        stage('Build') {
    steps {
        dir('Cucumber_BBD_Jenkins') {
            bat 'mvn clean'
        }
    }
}
   stage('Compile') {
            steps {
                dir('Cucumber_BBD_Jenkins') {
                    bat 'mvn compile'
                }
            }
        }      
 
        stage('Test') {
    steps {
        dir('Cucumber_BBD_Jenkins') {
            bat 'mvn test'
        }
    }
}
 
       
       stage('Package') {
    steps {
        dir('Cucumber_BBD_Jenkins') {
            bat 'mvn package'
        }
    }
}
        stage('Docker Build') {
    steps {
        bat 'docker build -t cucumber-framework .'
    }
}
 
       stage('Docker Run') {
    steps {
        bat 'docker run --rm cucumber-framework'
    }
    }
}
 
    post {
        success {
            echo 'Build Successful'
        }
 
        failure {
            echo 'Build Failed'
        }
    }
}

