pipeline {
    agent any
 
    tools {
        maven 'Maven3'
        jdk  'JDK'
    }
 
    stages {
 
        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/codingwithdev28/DemocartAssign.git'
            }
        }
 
        stage('Build') {
    steps {
        dir('Cucumber_BBD_Jenkins') {
            bat 'mvn clean'
        }
    }
}
   stage('Compile') {
            steps {
                dir('Cucumber_BBD_Jenkins') {
                    bat 'mvn compile'
                }
            }
        }      
 
        stage('Test') {
    steps {
        dir('Cucumber_BBD_Jenkins') {
            bat 'mvn test'
        }
    }
}
 
       
       stage('Package') {
    steps {
        dir('Cucumber_BBD_Jenkins') {
            bat 'mvn package'
        }
    }
}
        stage('Docker Build') {
    steps {
        bat 'docker build -t cucumber-framework .'
    }
}
 
       stage('Docker Run') {
    steps {
        bat 'docker run --rm cucumber-framework'
    }
    }
}
 
    post {
        success {
            echo 'Build Successful'
        }
 
        failure {
            echo 'Build Failed'
        }
    }
}
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
         https://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <groupId>com.opencart</groupId>
    <artifactId>OpenCartFramework</artifactId>
    <version>1.0</version>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
    </properties>

    <dependencies>

        <!-- Selenium -->
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
            <version>4.33.0</version>
        </dependency>

        <!-- TestNG -->
        <dependency>
            <groupId>org.testng</groupId>
            <artifactId>testng</artifactId>
            <version>7.11.0</version>
            <scope>test</scope>
        </dependency>

        <!-- WebDriverManager -->
        <dependency>
            <groupId>io.github.bonigarcia</groupId>
            <artifactId>webdrivermanager</artifactId>
            <version>6.1.0</version>
        </dependency>

        <!-- Apache POI -->
        <dependency>
            <groupId>org.apache.poi</groupId>
            <artifactId>poi-ooxml</artifactId>
            <version>5.4.1</version>
        </dependency>

    </dependencies>

    <build>
        <plugins>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>3.5.3</version>

                <configuration>
                    <suiteXmlFiles>
                        <suiteXmlFile>testng.xml</suiteXmlFile>
                    </suiteXmlFiles>
                </configuration>

            </plugin>

        </plugins>
    </build>

</project>
