pipeline {
    agent any
 
    tools {
        maven 'Maven3'
        jdk  'JDK'
    }
 
    stages {
 
        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/codingwithdev28/DemocartAssign.git'
            }
        }
 
        stage('Build') {
    steps {
        dir('Cucumber_BBD_Jenkins') {
            bat 'mvn clean'
        }
    }
}
   stage('Compile') {
            steps {
                dir('Cucumber_BBD_Jenkins') {
                    bat 'mvn compile'
                }
            }
        }      
 
        stage('Test') {
    steps {
        dir('Cucumber_BBD_Jenkins') {
            bat 'mvn test'
        }
    }
}
 
       
       stage('Package') {
    steps {
        dir('Cucumber_BBD_Jenkins') {
            bat 'mvn package'
        }
    }
}
        stage('Docker Build') {
    steps {
        bat 'docker build -t cucumber-framework .'
    }
}
 
       stage('Docker Run') {
    steps {
        bat 'docker run --rm cucumber-framework'
    }
    }
}
 
    post {
        success {
            echo 'Build Successful'
        }
 
        failure {
            echo 'Build Failed'
        }
    }
}
<dependency>
    <groupId>org.seleniumhq.selenium</groupId>
    <artifactId>selenium-java</artifactId>
    <version>4.33.0</version>
</dependency>

<dependency>
    <groupId>org.testng</groupId>
    <artifactId>testng</artifactId>
    <version>7.11.0</version>
    <scope>test</scope>
</dependency>

<dependency>
    <groupId>io.github.bonigarcia</groupId>
    <artifactId>webdrivermanager</artifactId>
    <version>6.1.0</version>
</dependency>

<dependency>
    <groupId>org.apache.poi</groupId>
    <artifactId>poi-ooxml</artifactId>
    <version>5.4.1</version>
</dependency>

<dependency>
    <groupId>com.aventstack</groupId>
    <artifactId>extentreports</artifactId>
    <version>5.1.2</version>
</dependency>

<dependency>
    <groupId>org.apache.logging.log4j</groupId>
    <artifactId>log4j-core</artifactId>
    <version>2.24.3</version>
</dependency>

<dependency>
    <groupId>org.apache.logging.log4j</groupId>
    <artifactId>log4j-api</artifactId>
    <version>2.24.3</version>
</dependency>

<dependency>
    <groupId>commons-io</groupId>
    <artifactId>commons-io</artifactId>
    <version>2.18.0</version>
</dependency>
<build>
    <plugins>
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-surefire-plugin</artifactId>
            <version>3.5.3</version>

            <configuration>
                <suiteXmlFiles>
                    <suiteXmlFile>testng.xml</suiteXmlFile>
                </suiteXmlFiles>
            </configuration>
        </plugin>
    </plugins>
</build>

